In [9]:
%config IPCompleter.greedy=True

In [10]:
import pandas as pd

In [11]:
mainpath = "../conjuntodatos"
filename = "titanic/titanic3.csv"
fullpath = mainpath + "/" + filename

In [12]:
fullpath

'../conjuntodatos/titanic/titanic3.csv'

In [13]:
data = pd.read_csv(fullpath)

In [17]:
data.tail(2)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
1307,3,0,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.225,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.875,NaN,S,NaN,NaN,NaN

In [18]:
data2 = pd.read_csv(mainpath + "/" + "customer-churn-model/Customer Churn Model.txt")

In [20]:
data2.head()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.

#vamos a cargar datos de un encabezado a otro archivo

# vamos a cargar datos de un encabezado a otro archivo

In [21]:
data2.columns.values

array(['State', 'Account Length', 'Area Code', 'Phone', "Int'l Plan",
       'VMail Plan', 'VMail Message', 'Day Mins', 'Day Calls',
       'Day Charge', 'Eve Mins', 'Eve Calls', 'Eve Charge', 'Night Mins',
       'Night Calls', 'Night Charge', 'Intl Mins', 'Intl Calls',
       'Intl Charge', 'CustServ Calls', 'Churn?'], dtype=object)

In [22]:
data_cols = pd.read_csv(mainpath + "/" + "customer-churn-model/Customer Churn Columns.csv")

In [23]:
data_col_list = data_cols["Column_Names"].tolist()

In [24]:
data2 = pd.read_csv(mainpath + "/" + "customer-churn-model/Customer Churn Model.txt",
                   header = None, names= data_col_list)

In [25]:
data2.columns.values

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U'], dtype=object)

,A,B,C,D,E,F,G,H,I,J,...,L,M,N,O,P,Q,R,S,T,U
0,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
1,KS,128,415,382-4657,no,yes,25,265.100000,110,45.070000,...,99,16.780000,244.700000,91,11.010000,10.000000,3,2.700000,1,False.
2,OH,107,415,371-7191,no,yes,26,161.600000,123,27.470000,...,103,16.620000,254.400000,103,11.450000,13.700000,3,3.700000,1,False.
3,NJ,137,415,358-1921,no,no,0,243.400000,114,41.380000,...,110,10.300000,162.600000,104,7.320000,12.200000,5,3.290000,0,False.
4,OH,84,408,375-9999,yes,no,0,299.400000,71,50.900000,...,88,5.260000,196.900000,89,8.860000,6.600000,7,1.780000,2,False.
5,OK,75,415,330-6626,yes,no,0,166.700000,113,28.340000,...,122,12.610000,186.900000,121,8.410000,10.100000,3,2.730000,3,False.
6,AL,118,510,391-8027,yes,no,0,223.400000,98,37.980000,...,101,18.750000,203.900000,118,9.180000,6.300000,6,1.700000,0,False.
7,MA,121,510,355-9993,no,yes,24,218.200000,88,37.090000,...,108,29.620000,212.600000,118,9.570000,7.500000,7,2.030000,3,False.
8,MO,147,415,329-9001,yes,no,0,157.000000,79,26.690000,...,94,8.760000,211.800000,96,9.530000,7.100000,6,1.920000,0,False.
9,LA,117,408,335-4719,no,no,0,184.500000,97,31.370000,...,80,29.890000,215.800000,90,9.710000,8.700000,4,2.350000,1,False.
10,WV,141,415,330-8173,yes,yes,37,258.600000,84,43.960000,...,111,18.870000,326.400000,97,14.690000,11.200000,5,3.020000,0,False.
11,IN,65,415,329-6603,no,no,0,129.100000,137,21.950000,...,83,19.420000,208.800000,111,9.400000,12.700000,6,3.430000,4,True.
12,RI,74,415,344-9403,no,no,0,187.700000,127,31.910000,...,148,13.890000,196.000000,94,8.820000,9.100000,5,2.460000,0,False.
13,IA,168,408,363-1107,no,no,0,128.800000,96,21.900000,...,71,8.920000,141.100000,128,6.350000,11.200000,2,3.020000,1,False.
14,MT,95,510,394-8006,no,no,0,156.600000,88,26.620000,...,75,21.050000,192.300000,115,8.650000,12.300000,5,3.320000,3,False.
15,IA,62,415,366-9238,no,no,0,120.700000,70,20.520000,...,76,26.110000,203.000000,99,9.140000,13.100000,6,3.540000,4,False.
16,NY,161,415,351-7269,no,no,0,332.900000,67,56.590000,...,97,27.010000,160.600000,128,7.230000,5.400000,9,1.460000,4,True.
17,ID,85,408,350-8884,no,yes,27,196.400000,139,33.390000,...,90,23.880000,89.300000,75,4.020000,13.800000,4,3.730000,1,False.
18,VT,93,510,386-2923,no,no,0,190.700000,114,32.420000,...,111,18.550000,129.600000,121,5.830000,8.100000,3,2.190000,3,False.
19,VA,76,510,356-2992,no,yes,33,189.700000,66,32.250000,...,65,18.090000,165.700000,108,7.460000,10.000000,5,2.700000,1,False.
20,TX,73,415,373-2782,no,no,0,224.400000,90,38.150000,...,88,13.560000,192.800000,74,8.680000,13.000000,2,3.510000,1,False.
21,FL,147,415,396-5800,no,no,0,155.100000,117,26.370000,...,93,20.370000,208.800000,133,9.400000,10.600000,4,2.860000,0,False.
22,CO,77,408,393-7984,no,no,0,62.400000,89,10.610000,...,121,14.440000,209.600000,64,9.430000,5.700000,6,1.540000,5,True.
23,AZ,130,415,358-1958,no,no,0,183.000000,112,31.110000,...,99,6.200000,181.800000,78,8.180000,9.500000,19,2.570000,0,False.
24,SC,111,415,350-2565,no,no,0,110.400000,103,18.770000,...,102,11.670000,189.600000,105,8.530000,7.700000,6,2.080000,2,False.
25,VA,132,510,343-4696,no,no,0,81.100000,86,13.790000,...,72,20.840000,237.000000,115,10.670000,10.300000,2,2.780000,0,False.
26,NE,174,415,331-3698,no,no,0,124.300000,76,21.130000,...,112,23.550000,250.700000,115,11.280000,15.500000,5,4.190000,3,False.
27,WY,57,408,357-3817,no,yes,39,213.000000,115,36.210000,...,112,16.240000,182.700000,115,8.220000,9.500000,3,2.570000,0,False.
28,MT,54,408,418-6412,no,no,0,134.300000,73,22.830000,...,100,13.220000,102.100000,68,4.590000,14.700000,4,3.970000,3,False.
29,MO,20,415,353-2630,no,no,0,190.000000,109,32.300000,...,84,21.950000,181.500000,102,8.170000,6.300000,6,1.700000,0,False.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3304,WI,114,415,373-7308,no,yes,26,137.100000,88,23.310000,...,125,13.230000,247.600000,94,11.140000,11.500000,7,3.110000,2,False.
3305,IL,71,510,330-7137,yes,no,0,186.100000,114,31.640000,...,140,16.880000,206.500000,80,9.290000,13.800000,5,3.730000,4,True.
3306,IN,58,415,406-8445,no,yes,22,224.100000,127,38.100000,...,85,20.300000,174.200000,86,7.840000,11.500000,7,3.110000,2,False.
3307,AL,106,408,404-5283,no,yes,29,83.600000,131,14.210000,...,131,17.330000,229.500000,73,10.330000,8.100000,3,2.190000,1,False.
3308,OK,172,408,398-3632,no,no,0,203.900000,109,34.660000,...,123,19.890000,160.700000,65,7.230000,17.800000,4,4.810000,4,False.
3309,IA,45,415,399-5763,no,no,0,211.300000,87,35.920000,...,97,14.080000,265.900000,72,11.970000,13.300000,6,3.590000,1,False.
3310,VT,100,408,340-9449,yes,no,0,219.400000,112,37.300000,...,102,19.180000,255.300000,95,11.490000,12.000000,4,3.240000,4,False.
3311,NY,94,415,363-1123,no,no,0,190.400000,91,32.370000,...,107,7.820000,224.800000,108,10.120000,13.600000,17,3.670000,2,False.
3312,LA,128,415,361-2170,no,no,0,147.700000,94,25.110000,...,83,24.080000,188.300000,124,8.470000,6.900000,5,1.860000,2,False.
3313,SC,181,408,406-6304,no,no,0,229.900000,130,39.080000,...,93,12.270000,262.400000,110,11.810000,14.200000,4,3.830000,2,False.
3314,ID,127,408,392-5090,no,no,0,102.800000,128,17.480000,...,95,12.210000,191.400000,97,8.610000,10.000000,5,2.700000,1,False.
3315,MO,89,415,373-7713,no,no,0,178.700000,81,30.380000,...,74,19.860000,131.900000,120,5.940000,9.100000,4,2.460000,1,False.
3316,ME,149,415,392-1376,no,yes,18,148.500000,106,25.250000,...,106,9.730000,178.300000,98,8.020000,6.500000,4,1.760000,0,False.
3317,MS,103,510,390-6388,no,yes,29,164.100000,111,27.900000,...,96,18.620000,220.300000,108,9.910000,12.300000,9,3.320000,0,False.
3318,SD,163,415,379-7290,yes,no,0,197.200000,90,33.520000,...,113,16.020000,211.100000,94,9.500000,7.800000,8,2.110000,1,False.
3319,OK,52,415,397-9928,no,no,0,124.900000,131,21.230000,...,118,25.540000,192.500000,106,8.660000,11.600000,4,3.130000,2,False.
3320,WY,89,415,378-6924,no,no,0,115.400000,99,19.620000,...,115,17.840000,280.900000,112,12.640000,15.900000,6,4.290000,3,False.
3321,GA,122,510,411-5677,yes,no,0,140.000000,101,23.800000,...,77,16.690000,120.100000,133,5.400000,9.700000,4,2.620000,4,True.
3322,VT,60,415,400-2738,no,no,0,193.900000,118,32.960000,...,110,7.230000,210.100000,134,9.450000,13.200000,8,3.560000,3,False.
3323,MD,62,408,409-1856,no,no,0,321.100000,105,54.590000,...,122,22.570000,180.500000,72,8.120000,11.500000,2,3.110000,4,True.
3324,IN,117,415,362-5899,no,no,0,118.400000,126,20.130000,...,97,21.190000,227.000000,56,10.220000,13.600000,3,3.670000,5,True.
3325,WV,159,415,377-1164,no,no,0,169.800000,114,28.870000,...,105,16.800000,193.700000,82,8.720000,11.600000,4,3.130000,1,False.
3326,OH,78,408,368-8555,no,no,0,193.400000,99,32.880000,...,88,9.940000,243.300000,109,10.950000,9.300000,4,2.510000,2,False.
3327,OH,96,415,347-6812,no,no,0,106.600000,128,18.120000,...,87,24.210000,178.900000,92,8.050000,14.900000,7,4.020000,1,False.
3328,SC,79,415,348-3830,no,no,0,134.700000,98,22.900000,...,68,16.120000,221.400000,128,9.960000,11.800000,5,3.190000,2,False.
3329,AZ,192,415,414-4276,no,yes,36,156.200000,77,26.550000,...,126,18.320000,279.100000,83,12.560000,9.900000,6,2.670000,2,False.
3330,WV,68,415,370-3271,no,no,0,231.100000,57,39.290000,...,55,13.040000,191.300000,123,8.610000,9.600000,4,2.590000,3,False.
3331,RI,28,510,328-8230,no,no,0,180.800000,109,30.740000,...,58,24.550000,191.900000,91,8.640000,14.100000,6,3.810000,2,False.
3332,CT,184,510,364-6381,yes,no,0,213.800000,105,36.350000,...,84,13.570000,139.200000,137,6.260000,5.000000,10,1.350000,2,False.
3333,TN,74,415,400-4344,no,yes,25,234.400000,113,39.850000,...,82,22.600000,241.400000,77,10.860000,13.700000,4,3.700000,0,False.

# lecrura del mÃ©todo open

In [27]:
data3 = open(mainpath + "/" + "customer-churn-model/Customer Churn Model.txt",'r')

In [28]:
cols = data3.readline().strip().split(",")

In [29]:
n_cols = len(cols)

In [30]:
n_cols

21

In [31]:
counter = 0
main_dict = {}
for col in cols:
    main_dict[col] = []

In [34]:
for line in data3:
    values = line.strip().split(",")
    for i in range(len(cols)):
        main_dict[cols[i]].append(values[i])
    counter += 1

In [40]:
type(data3)

_io.TextIOWrapper

In [39]:
n_cols

21